service: aptos
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'test'}
  region: eu-west-1

functions:
  getBlocks:
    handler: functions/get-blocks.handler



